# Bloc obligatoire dans une configuration Nginx.
# Ici on ne configure pas d'événements particuliers.
events {}

# Bloc de configuration HTTP.
http {
  # upstream crée un groupe de serveurs backend.
  # Nginx choisira une API dans cette liste.
  upstream trainshop_api {
    # Chaque nom correspond au nom d'un service Docker Compose.
    server api1:3000;
    server api2:3000;
    server api3:3000;
  }

  # Serveur Nginx exposé sur le port 80 dans le container.
  server {
    listen 80;

    # Pour toutes les routes, on transmet la requête vers le groupe d'API.
    location / {
      # proxy_pass fait passer la requête à une API disponible.
      proxy_pass http://trainshop_api;
    }
  }
}